### ISSUE TITLE
Do schema management on our own.

### ISSUE THREAD

**Issue by mjpitz** [mjpitz/cognative#67]
Got bit by schema management again so here's the basic idea for how to get a migration script up and running in `docker-compose.yaml`.

```yaml
  metrics-collector-migrate:
    depends_on:
      metrics-clickhouse:
        condition: service_healthy
    image: clickhouse/clickhouse-server:24.9 # amd64 + arm64
    restart: on-failure
    entrypoint: clickhouse-client
    command:
      - --multiline
      - --progress
      - --stacktrace
      - --host=metrics-clickhouse
      - --database=otel
      - --user=clickhouse
      - --password=clickhouse
      - --queries-file=/etc/collector/schema/histogram_metrics.sql
      - --queries-file=/etc/collector/schema/logs.sql
      - --queries-file=/etc/collector/schema/sum_metrics.sql
      - --queries-file=/etc/collector/schema/summary_metrics.sql
      - --queries-file=/etc/collector/schema/traces.sql
    networks:
      - shared
    volumes:
      - ./collector:/etc/collector
      - certs:/etc/ssl/certs
```

The schema files can be found here: `https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-contrib/refs/heads/main/exporter/clickhouseexporter/example/default_ddl/{filename}`
